services:
  multiplayer-server:
    build: .
    container_name: multiplayer-server
    restart: unless-stopped

    ports:
      - "${PORT:-17829}:17829"

    environment:
      PORT: 17829

    volumes:
      - ./multiplayer:/app/multiplayer
